# Generated by Django 5.0.1 on 2024-01-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('mood', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
